import Chat from "@/components/Chat"
import "./globals.css"
import { Rubik } from "next/font/google"
import Providers from "@/components/Providers"

const rubikFont = Rubik({ subsets: ["latin"] })

export const metadata = {
  title: "Pillwise | Chatbot",
  description: "Generated by pillwise devtools",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={rubikFont.className}>
          <Chat />
          {children}
        </body>
      </Providers>
    </html>
  )
}
